name: CI
on: 
  pull_request: 
    branches: main
  workflow_dispatch:

jobs:
  test_ci:
      runs-on: ubuntu-latest
      
      steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: 3.x
          
      - name: Make dotenv
        run: |
          touch .env
          echo "${{ secrets.ENV }}" > .env
          ls
        shell: bash
        
      - name: Install packages
        run: flutter pub get
        
      - name: Test
        run: flutter test

  lint_ci:
      runs-on: ubuntu-latest
      
      steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: 3.x
          
      - name: Make dotenv
        run: |
          touch .env
          echo "${{ secrets.ENV }}" > .env
          ls
        shell: bash    
        
      - name: Install packages
        run: flutter pub get
      
      - name: Linter
        run: flutter analyze
        
